## TOML Uranio
db = "mongo"
encryption_rounds = 12
max_password_length = 58
storage = 'aws'
connect_on_init = false
prefix_api = '/uranio/api'
prefix_log = '/logs'
lambda = 'netlify'
fetch = 'axios'
[service]
	platform = 'express'
	protocol = 'http'
	domain = 'localhost'
	port = 7775
	url = 'http://localhost:7775/uranio/api'
[dev.service]
	protocol = 'http'
	domain = 'localhost'
	port = 7775
	url = 'http://localhost:7775/uranio/api'
[client.panel]
	protocol = 'http'
	domain = 'localhost'
	port = 5454
[client.dev.panel]
	protocol = 'http'
	domain = 'localhost'
	port = 4477
[client.fetch]
	url = 'http://localhost:5454/uranio/api'
[client.dev.fetch]
	url = 'http://localhost:4477/uranio/api'
[log]
	debug_info = true
	color = true
	time_format = "yyyy-mm-dd'T'HH:MM:ss:l"
	max_str_length = 174
	prefix = ''
	prefix_type = false
[dev.log]
	debug_info = false
	color = true
	time_format = "yyyy-mm-dd'T'HH:MM:ss:l"
	max_str_length = 174
	prefix = ''
	prefix_type = false
[client.log]
	debug_info = false
	color = false
	time_format = "HH:MM:ss:l"
	max_str_length = 174
	prefix = ''
	prefix_type = false
[client.dev.log]
	debug_info = false
	color = false
	time_format = "yyyy-mm-dd'T'HH:MM:ss:l"
	max_str_length = 174
	prefix = ''
	prefix_type = false
