## TOML Uranio
db = "mongo"
encryption_rounds = 12
max_password_length = 58
storage = 'aws'
connect_on_init = true
prefix_api = '/uranio/api'
prefix_log = '/log'
lambda = 'netlify'
fetch = 'axios'
[service]
	platform = 'express'
	protocol = 'http'
	domain = 'localhost'
	port = 7777
	url = 'http://localhost:7777/uranio/api'
[service.dev]
	protocol = 'http'
	domain = 'localhost'
	port = 7772
	url = 'http://localhost:7772/uranio/api'
[log]
	debug_info = true
	color = true
	time_format = "yyyy-mm-dd'T'HH:MM:ss:l"
	max_str_length = 174
	prefix = ''
	prefix_type = false
[log.dev]
	debug_info = true
	color = true
	time_format = "yyyy-mm-dd'T'HH:MM:ss:l"
	max_str_length = 174
	prefix = ''
	prefix_type = false
[client.service]
	url = 'http://localhost:7777/uranio/api'
[client.service.dev]
	url = 'http://localhost:7772/uranio/api'
[client.log]
	debug_info = false
	color = false
	time_format = "yyyy-mm-dd'T'HH:MM:ss:l"
	max_str_length = 174
	prefix = ''
	prefix_type = false
[client.log.dev]
	debug_info = false
	color = false
	time_format = "yyyy-mm-dd'T'HH:MM:ss:l"
	max_str_length = 174
	prefix = ''
	prefix_type = false
