## TOML Uranio
db = "mongo"
encryption_rounds = 12
max_password_length = 58
storage = 'aws'
connect_on_init = true
prefix_api = '/uranio/api'
lambda = 'netlify'
fetch = 'axios'
[service]
	platform = 'express'
	protocol = 'http'
	domain = 'localhost'
	port = 7777
	[dev]
		protocol = 'http'
		domain = 'localhost'
		port = 7777
